// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestAPIDemo.Data;

#nullable disable

namespace RestAPIDemo.Migrations
{
    [DbContext(typeof(RestAPIDbContext))]
    partial class RestAPIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestAPIDemo.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Playing football on weekends",
                            Title = "Football"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Trying out new recipes",
                            Title = "Cooking"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Landscape photography",
                            Title = "Photography"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Reading novels and articles",
                            Title = "Reading"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Video games and board games",
                            Title = "Gaming"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Playing instruments or singing",
                            Title = "Music"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Exploring nature trails",
                            Title = "Hiking"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Creating artwork",
                            Title = "Painting"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Visiting new countries and cities",
                            Title = "Traveling"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Swimming in pools and lakes",
                            Title = "Swimming"
                        });
                });

            modelBuilder.Entity("RestAPIDemo.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonInterestId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonInterestId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PersonInterestId = 1,
                            Url = "https://www.football.com"
                        },
                        new
                        {
                            Id = 2,
                            PersonInterestId = 2,
                            Url = "https://www.recipes.com"
                        },
                        new
                        {
                            Id = 3,
                            PersonInterestId = 3,
                            Url = "https://www.cookingblog.com"
                        },
                        new
                        {
                            Id = 4,
                            PersonInterestId = 4,
                            Url = "https://www.photography.com"
                        },
                        new
                        {
                            Id = 5,
                            PersonInterestId = 5,
                            Url = "https://www.reading.com"
                        },
                        new
                        {
                            Id = 6,
                            PersonInterestId = 6,
                            Url = "https://www.gaming.com"
                        },
                        new
                        {
                            Id = 7,
                            PersonInterestId = 7,
                            Url = "https://www.music.com"
                        },
                        new
                        {
                            Id = 8,
                            PersonInterestId = 8,
                            Url = "https://www.hiking.com"
                        },
                        new
                        {
                            Id = 9,
                            PersonInterestId = 9,
                            Url = "https://www.painting.com"
                        },
                        new
                        {
                            Id = 10,
                            PersonInterestId = 10,
                            Url = "https://www.traveling.com"
                        },
                        new
                        {
                            Id = 11,
                            PersonInterestId = 11,
                            Url = "https://www.swimming.com"
                        },
                        new
                        {
                            Id = 12,
                            PersonInterestId = 12,
                            Url = "https://www.footballnews.com"
                        },
                        new
                        {
                            Id = 13,
                            PersonInterestId = 13,
                            Url = "https://www.cookingfun.com"
                        });
                });

            modelBuilder.Entity("RestAPIDemo.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Alice",
                            LastName = "Andersson",
                            PhoneNumber = "0701000001"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Bob",
                            LastName = "Berg",
                            PhoneNumber = "0701000002"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Charlie",
                            LastName = "Carlsson",
                            PhoneNumber = "0701000003"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Diana",
                            LastName = "Dahl",
                            PhoneNumber = "0701000004"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Erik",
                            LastName = "Eklund",
                            PhoneNumber = "0701000005"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Fiona",
                            LastName = "Fredriksson",
                            PhoneNumber = "0701000006"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Gustav",
                            LastName = "Gustafsson",
                            PhoneNumber = "0701000007"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Hanna",
                            LastName = "Hansson",
                            PhoneNumber = "0701000008"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Isak",
                            LastName = "Ivarsson",
                            PhoneNumber = "0701000009"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Julia",
                            LastName = "Johansson",
                            PhoneNumber = "0701000010"
                        });
                });

            modelBuilder.Entity("RestAPIDemo.Models.PersonInterest", b =>
                {
                    b.Property<int>("PersonInterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonInterestId"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("PersonInterestId");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonInterests");

                    b.HasData(
                        new
                        {
                            PersonInterestId = 1,
                            InterestId = 1,
                            PersonId = 1
                        },
                        new
                        {
                            PersonInterestId = 2,
                            InterestId = 2,
                            PersonId = 1
                        },
                        new
                        {
                            PersonInterestId = 3,
                            InterestId = 2,
                            PersonId = 2
                        },
                        new
                        {
                            PersonInterestId = 4,
                            InterestId = 3,
                            PersonId = 2
                        },
                        new
                        {
                            PersonInterestId = 5,
                            InterestId = 4,
                            PersonId = 3
                        },
                        new
                        {
                            PersonInterestId = 6,
                            InterestId = 5,
                            PersonId = 3
                        },
                        new
                        {
                            PersonInterestId = 7,
                            InterestId = 6,
                            PersonId = 4
                        },
                        new
                        {
                            PersonInterestId = 8,
                            InterestId = 7,
                            PersonId = 5
                        },
                        new
                        {
                            PersonInterestId = 9,
                            InterestId = 8,
                            PersonId = 6
                        },
                        new
                        {
                            PersonInterestId = 10,
                            InterestId = 9,
                            PersonId = 7
                        },
                        new
                        {
                            PersonInterestId = 11,
                            InterestId = 10,
                            PersonId = 8
                        },
                        new
                        {
                            PersonInterestId = 12,
                            InterestId = 1,
                            PersonId = 9
                        },
                        new
                        {
                            PersonInterestId = 13,
                            InterestId = 2,
                            PersonId = 10
                        });
                });

            modelBuilder.Entity("RestAPIDemo.Models.Link", b =>
                {
                    b.HasOne("RestAPIDemo.Models.PersonInterest", "PersonInterest")
                        .WithMany()
                        .HasForeignKey("PersonInterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonInterest");
                });

            modelBuilder.Entity("RestAPIDemo.Models.PersonInterest", b =>
                {
                    b.HasOne("RestAPIDemo.Models.Interest", "Interest")
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestAPIDemo.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
